"""
Conversation simulation service.

Simulates multi-turn conversations between two Digital Twins.
In production, this uses an LLM to generate realistic dialogue.
Currently uses template-based simulation as a fallback.
"""
from datetime import datetime, timezone, timedelta
from typing import List, Dict, Any
from app.schemas import (
    ConversationRequest,
    ConversationResponse,
    ConversationMessage,
)


def _extract_interests(profile: Dict[str, Any]) -> List[str]:
    """Safely extract interests from a profile dictionary."""
    return profile.get("interests", [])


def _extract_values(profile: Dict[str, Any]) -> List[str]:
    """Safely extract values from a profile dictionary."""
    return profile.get("values", [])


def _find_common_ground(profile_a: Dict[str, Any], profile_b: Dict[str, Any]) -> Dict[str, Any]:
    """Find shared interests, values, and topics between two profiles."""
    interests_a = set(i.lower() for i in _extract_interests(profile_a))
    interests_b = set(i.lower() for i in _extract_interests(profile_b))
    common_interests = interests_a & interests_b

    values_a = set(v.lower() for v in _extract_values(profile_a))
    values_b = set(v.lower() for v in _extract_values(profile_b))
    common_values = values_a & values_b

    return {
        "common_interests": list(common_interests),
        "common_values": list(common_values),
        "unique_a": list(interests_a - interests_b),
        "unique_b": list(interests_b - interests_a),
    }


def _assess_emotional_tone(common_ground: Dict[str, Any]) -> str:
    """Determine the emotional tone based on common ground."""
    total_shared = len(common_ground["common_interests"]) + len(common_ground["common_values"])
    if total_shared >= 5:
        return "warm and enthusiastic"
    elif total_shared >= 3:
        return "friendly and curious"
    elif total_shared >= 1:
        return "polite and exploratory"
    else:
        return "cordial but reserved"


def _generate_conversation_turns(
    twin_a: Dict[str, Any],
    twin_b: Dict[str, Any],
    common_ground: Dict[str, Any],
    max_turns: int,
    context: str,
) -> List[ConversationMessage]:
    """
    Generate simulated conversation turns between two twins.

    In production, each turn would be generated by an LLM with the twin's
    system prompt as context. This template version creates structured dialogue
    that touches on key compatibility dimensions.
    """
    messages: List[ConversationMessage] = []
    base_time = datetime.now(timezone.utc)
    common_interests = common_ground["common_interests"]
    common_values = common_ground["common_values"]

    # Conversation phases
    phases = [
        ("greeting", _greeting_exchange),
        ("interests", _interests_exchange),
        ("values", _values_exchange),
        ("goals", _goals_exchange),
        ("lifestyle", _lifestyle_exchange),
        ("closing", _closing_exchange),
    ]

    turn_index = 0
    for phase_name, phase_fn in phases:
        if turn_index >= max_turns:
            break
        phase_messages = phase_fn(
            twin_a, twin_b, common_ground, base_time, turn_index
        )
        for msg in phase_messages:
            if turn_index >= max_turns:
                break
            messages.append(msg)
            turn_index += 1

    return messages


def _greeting_exchange(
    twin_a: Dict[str, Any], twin_b: Dict[str, Any],
    common_ground: Dict[str, Any], base_time: datetime, start_idx: int,
) -> List[ConversationMessage]:
    """Generate greeting phase messages."""
    return [
        ConversationMessage(
            role="twin_a",
            content="Hi there! I'm really looking forward to getting to know you. What's been on your mind lately?",
            timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
        ),
        ConversationMessage(
            role="twin_b",
            content="Hey! Great to connect. I've been thinking a lot about personal growth and what really matters in life. How about you?",
            timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
        ),
    ]


def _interests_exchange(
    twin_a: Dict[str, Any], twin_b: Dict[str, Any],
    common_ground: Dict[str, Any], base_time: datetime, start_idx: int,
) -> List[ConversationMessage]:
    """Generate interest exploration messages."""
    common = common_ground["common_interests"]
    unique_a = common_ground.get("unique_a", [])

    if common:
        interests_str = ", ".join(common[:3])
        return [
            ConversationMessage(
                role="twin_a",
                content=f"I noticed we both enjoy {interests_str}! That's exciting. What got you into those?",
                timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
            ),
            ConversationMessage(
                role="twin_b",
                content=f"Oh, that's so cool that you're into those too! For me, it started as a way to explore new perspectives. I find that {common[0] if common else 'these interests'} really helps me grow as a person.",
                timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
            ),
        ]
    elif unique_a:
        return [
            ConversationMessage(
                role="twin_a",
                content=f"I'm really passionate about {', '.join(unique_a[:2])}. What are you into?",
                timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
            ),
            ConversationMessage(
                role="twin_b",
                content="That sounds fascinating! I'm into different things but I love hearing about other people's passions. Tell me more about what draws you to those.",
                timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
            ),
        ]
    return []


def _values_exchange(
    twin_a: Dict[str, Any], twin_b: Dict[str, Any],
    common_ground: Dict[str, Any], base_time: datetime, start_idx: int,
) -> List[ConversationMessage]:
    """Generate values discussion messages."""
    common_values = common_ground["common_values"]
    if common_values:
        values_str = " and ".join(common_values[:2])
        return [
            ConversationMessage(
                role="twin_a",
                content=f"I really value {values_str} in my life. These principles guide a lot of my decisions. What values are most important to you?",
                timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
            ),
            ConversationMessage(
                role="twin_b",
                content=f"Those resonate with me deeply! I think {values_str} {'are' if len(common_values) > 1 else 'is'} fundamental to building any meaningful relationship. It's refreshing to meet someone who feels the same way.",
                timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
            ),
        ]
    return [
        ConversationMessage(
            role="twin_a",
            content="What values are most important to you? I think understanding each other's core beliefs is key.",
            timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
        ),
        ConversationMessage(
            role="twin_b",
            content="Great question. I believe in being authentic and staying true to yourself. Honesty and growth are non-negotiable for me.",
            timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
        ),
    ]


def _goals_exchange(
    twin_a: Dict[str, Any], twin_b: Dict[str, Any],
    common_ground: Dict[str, Any], base_time: datetime, start_idx: int,
) -> List[ConversationMessage]:
    """Generate goals discussion messages."""
    return [
        ConversationMessage(
            role="twin_a",
            content="Where do you see yourself in the next few years? What are you working towards?",
            timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
        ),
        ConversationMessage(
            role="twin_b",
            content="I'm focused on personal growth and building meaningful connections. I want a relationship that supports both people's individual journeys. What about you?",
            timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
        ),
    ]


def _lifestyle_exchange(
    twin_a: Dict[str, Any], twin_b: Dict[str, Any],
    common_ground: Dict[str, Any], base_time: datetime, start_idx: int,
) -> List[ConversationMessage]:
    """Generate lifestyle discussion messages."""
    return [
        ConversationMessage(
            role="twin_a",
            content="How do you typically spend your weekends? I'm curious about your day-to-day life.",
            timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
        ),
        ConversationMessage(
            role="twin_b",
            content="I like to balance between being active and having downtime. Some weekends I'll explore new places, other times I'm happy with a good book or catching up with close friends.",
            timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
        ),
    ]


def _closing_exchange(
    twin_a: Dict[str, Any], twin_b: Dict[str, Any],
    common_ground: Dict[str, Any], base_time: datetime, start_idx: int,
) -> List[ConversationMessage]:
    """Generate closing phase messages."""
    return [
        ConversationMessage(
            role="twin_a",
            content="This has been a really great conversation. I feel like we have a lot in common and could build something meaningful.",
            timestamp=(base_time + timedelta(seconds=start_idx * 30)).isoformat(),
        ),
        ConversationMessage(
            role="twin_b",
            content="I agree! It's been wonderful getting to know you. I think there's real potential here for a genuine connection.",
            timestamp=(base_time + timedelta(seconds=(start_idx + 1) * 30)).isoformat(),
        ),
    ]


def _extract_topics(messages: List[ConversationMessage]) -> List[str]:
    """Extract discussed topics from conversation messages."""
    topics = set()
    topic_keywords = {
        "interests": ["interest", "passionate", "enjoy", "into", "hobby"],
        "values": ["value", "believe", "principle", "important", "matter"],
        "goals": ["goal", "future", "working towards", "see yourself", "aspire"],
        "lifestyle": ["weekend", "day-to-day", "routine", "spend time", "balance"],
        "personal growth": ["growth", "learn", "develop", "improve", "journey"],
        "relationships": ["relationship", "connection", "meaningful", "bond", "together"],
    }

    for msg in messages:
        content_lower = msg.content.lower()
        for topic, keywords in topic_keywords.items():
            if any(kw in content_lower for kw in keywords):
                topics.add(topic)

    return list(topics) if topics else ["general getting to know each other"]


def _generate_summary(
    messages: List[ConversationMessage],
    common_ground: Dict[str, Any],
    emotional_tone: str,
) -> str:
    """Generate a summary of the conversation."""
    num_turns = len(messages)
    common_interests = common_ground["common_interests"]
    common_values = common_ground["common_values"]

    parts = [f"A {num_turns}-turn conversation with a {emotional_tone} tone."]

    if common_interests:
        parts.append(f"Discovered shared interests in {', '.join(common_interests[:3])}.")
    if common_values:
        parts.append(f"Found alignment on values: {', '.join(common_values[:3])}.")

    parts.append("Both parties engaged constructively and explored key compatibility dimensions.")

    return " ".join(parts)


def simulate_conversation(data: ConversationRequest) -> ConversationResponse:
    """
    Simulate a conversation between two Digital Twins.

    In production, this orchestrates multi-turn LLM calls where each twin
    responds based on its system prompt and the conversation history.
    The template version creates structured dialogue covering key topics.

    Args:
        data: Conversation request with both twins' contexts.

    Returns:
        Complete conversation with messages, summary, topics, and tone.
    """
    profile_a = data.twinA.profile
    profile_b = data.twinB.profile

    common_ground = _find_common_ground(profile_a, profile_b)
    emotional_tone = _assess_emotional_tone(common_ground)

    messages = _generate_conversation_turns(
        twin_a=data.twinA.dict(),
        twin_b=data.twinB.dict(),
        common_ground=common_ground,
        max_turns=data.maxTurns,
        context=data.context,
    )

    topics = _extract_topics(messages)
    summary = _generate_summary(messages, common_ground, emotional_tone)

    return ConversationResponse(
        messages=messages,
        summary=summary,
        topicsDiscussed=topics,
        emotionalTone=emotional_tone,
    )
