export enum TwinStatus {
  CREATED = 'CREATED',
  ACTIVE = 'ACTIVE',
  SEARCHING = 'SEARCHING',
  TALKING = 'TALKING',
  EVALUATING = 'EVALUATING',
  MATCH_FOUND = 'MATCH_FOUND',
  SLEEPING = 'SLEEPING',
}
