export enum NotificationType {
  MATCH_FOUND = 'MATCH_FOUND',
  CONVERSATION_COMPLETE = 'CONVERSATION_COMPLETE',
  TWIN_UPDATED = 'TWIN_UPDATED',
  CONNECTION_REQUEST = 'CONNECTION_REQUEST',
  CONNECTION_ACCEPTED = 'CONNECTION_ACCEPTED',
  NEW_MESSAGE = 'NEW_MESSAGE',
}
